title: VeyDigital
description: AI, cloud analytics, and lightweight automations
url: "https://vey-digital.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

# Use a /_pages folder for standalone pages like About, Contact, etc.
collections:
  pages:
    output: true
    permalink: /:path/

# Optional defaults so pages render with a good layout without repeating front matter
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: false
