title: Vey Digital
description: Startup playbooks, videos, and guides
remote_theme: "mmistakes/minimal-mistakes"

# Build
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Theme options
minimal_mistakes_skin: default
locale: en-US
timezone: America/Los_Angeles
markdown: kramdown
permalink: /:categories/:title/
search: true
search_full_content: true

# Masthead / logo (add these files later if you have them)
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico

# Navigation pulls from _data/navigation.yml
# Pages you’ll create below:
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope: { path: "" }
    values:
      layout: single
  - scope: { path: "" , type: pages }
    values:
      layout: single
      sidebar: false

