title: VeyDigital
description: AI, cloud analytics, and lightweight automations
url: https://vey-digital.github.io
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
# theme: jekyll-theme-primer   # ← ensure this is removed or commented out

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

paginate: 0
