title: Vey Digital
logo: /assets/images/logo.png

description: Startup playbooks, videos, and guides

# Minimal Mistakes via remote_theme (supported by GitHub Pages)

minimal_mistakes_skin: default
markdown: kramdown
locale: en-US
timezone: America/Los_Angeles

# Enable the search icon like the demo
search: true
search_full_content: true
