title: VeyDigital
description: AI, cloud analytics, and lightweight automations
url: https://vey-digital.github.io
baseurl: ""   # keep empty for user.github.io root sites

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
# theme: jekyll-theme-primer   # ← make sure this is removed or commented out

# IMPORTANT: do NOT set `theme:` when using remote_theme
# theme: jekyll-theme-primer   # ← leave removed

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  # If you aren't using pagination, don't load it:
  # - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

# If you enabled jekyll-paginate before and got the "no index.html" warning,
# either add an index.html with paginator or just leave paginate disabled:
paginate: 0

# Optional: keeps junk out of the build
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
