title: VeyDigital
description: AI, cloud analytics, and lightweight automations

url: "https://vey-digital.github.io"
baseurl: ""  # user/org site -> keep empty

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Header / branding
logo: "/assets/veydigital+logo2.png"
masthead_title: ""   # hide text next to logo

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

# Optional: output "pages" collection with clean URLs
collections:
  pages:
    output: true
    permalink: /:path/

# Footer social links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vey-Digital"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/YourHandle"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/yourInvite"
