title: VeyDigital

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from

logo: /assets/veydigital_logo2.png
masthead_title: ""   # hide text next to logo

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/YourHandle"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vey-Digital"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/yourInviteCode"

