title: VeyDigital
description: AI, cloud analytics, and lightweight automations
url: "https://vey-digital.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM


collections:
  pages:
    output: true
    permalink: /:path/
