title: VeyDigital
description: AI news to skills. Lightweight analytics & automations.

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from

# Header / branding
logo: /assets/veydigital_logo2.png
masthead_title: ""   # show logo only, no duplicate text

# Locale / theme options
locale: en-US
timezone: America/Los_Angeles
minimal_mistakes_skin: default
search: true
search_full_content: true

# Blog list behavior
paginate: 9
paginate_path: "/blog/page:num/"
show_excerpts: true
excerpt_separator: "<!--more-->"
timezone: America/Los_Angeles
date_format: "%b %-d, %Y"   # e.g., Oct 5, 2025


# Footer social links
footer:
  align: center
  links:
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://twitter.com/YourHandle"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/Vey-Digital"
    - label: "Discord"
      icon: "fa-brands fa-discord"
      url: "https://discord.gg/yourInviteCode"


