title: VeyDigital
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

logo: /assets/veydigital_logo2@2x.png
masthead_title: ""   # show only the logo (prevents duplicate text)
